// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SFManagement.Data;

#nullable disable

namespace SFManagement.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250615234113_adjust WI model")]
    partial class adjustWImodel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SFManagement.Models.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("SFManagement.Models.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("SFManagement.Models.Closing.ClosingManager", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CalculatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DeleteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DoneAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("EditorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("End")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ManagerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("RakeBruto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalRakeDiscounts")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ClosingManagers");
                });

            modelBuilder.Entity("SFManagement.Models.Closing.ClosingNickname", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Balance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ClosingManagerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DeleteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("EditorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FatherNicknameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("FatherPercentual")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("NicknameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Rake")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Rakeback")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClosingManagerId");

                    b.ToTable("ClosingNicknames");
                });

            modelBuilder.Entity("SFManagement.Models.Closing.ClosingWallet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssetWalletId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClosingManagerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DeleteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("EditorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ReturnRake")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AssetWalletId");

                    b.HasIndex("ClosingManagerId");

                    b.ToTable("ClosingWallets");
                });

            modelBuilder.Entity("SFManagement.Models.Entities.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BankId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Complement")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Country")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DeleteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("EditorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("MemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Number")
                        .HasColumnType("int");

                    b.Property<Guid?>("PokerManagerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Postcode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("State")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("StreetAddress")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BankId")
                        .IsUnique()
                        .HasFilter("[BankId] IS NOT NULL");

                    b.HasIndex("ClientId")
                        .IsUnique()
                        .HasFilter("[ClientId] IS NOT NULL");

                    b.HasIndex("MemberId")
                        .IsUnique()
                        .HasFilter("[MemberId] IS NOT NULL");

                    b.HasIndex("PokerManagerId")
                        .IsUnique()
                        .HasFilter("[PokerManagerId] IS NOT NULL");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("SFManagement.Models.Entities.AssetWallet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AssetType")
                        .HasColumnType("int");

                    b.Property<Guid?>("BankId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("DefaultAgreedCommission")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("DeleteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("EditorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("InitialAssetAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("MemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PokerManagerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BankId");

                    b.HasIndex("ClientId");

                    b.HasIndex("MemberId");

                    b.HasIndex("PokerManagerId");

                    b.ToTable("AssetWallets");
                });

            modelBuilder.Entity("SFManagement.Models.Entities.AvgRate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeleteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("EditorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PokerManagerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Value")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("AvgRates");
                });

            modelBuilder.Entity("SFManagement.Models.Entities.BaseAssetHolder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cnpj")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Cpf")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DeleteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("EditorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("BaseAssetHolder");

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("SFManagement.Models.Entities.ContactPhone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BankId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("CountryCode")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DeleteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("EditorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("LocalCode")
                        .HasColumnType("int");

                    b.Property<Guid?>("MemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid?>("PokerManagerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SearchFor")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BankId");

                    b.HasIndex("ClientId");

                    b.HasIndex("MemberId");

                    b.HasIndex("PokerManagerId");

                    b.ToTable("ContactPhone");
                });

            modelBuilder.Entity("SFManagement.Models.Entities.InitialBalance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Balance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BalanceUnit")
                        .HasColumnType("int");

                    b.Property<Guid?>("BankId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("ConversionRate")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ConvertTo")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DeleteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("EditorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("MemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PokerManagerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BankId");

                    b.HasIndex("ClientId");

                    b.HasIndex("MemberId");

                    b.HasIndex("PokerManagerId");

                    b.ToTable("InitialBalances");
                });

            modelBuilder.Entity("SFManagement.Models.Entities.WalletIdentifier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AssetType")
                        .HasColumnType("int");

                    b.Property<Guid?>("AssetWalletId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BankId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("DefaultParentCommission")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("DefaultRakeCommission")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("DeleteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("EditorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("InputForTransactions")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid?>("MemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Pix")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("PokerManagerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AssetWalletId");

                    b.HasIndex("BankId");

                    b.HasIndex("ClientId");

                    b.HasIndex("MemberId");

                    b.HasIndex("PokerManagerId");

                    b.ToTable("WalletIdentifiers");
                });

            modelBuilder.Entity("SFManagement.Models.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DeleteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("EditorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("SFManagement.Models.Transactions.DigitalAssetTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ApprovedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AssetAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("AssetWalletId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("ConversionRate")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ConvertTo")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeleteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("EditorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ExcelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Profit")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Rate")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("TagId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TransactionDirection")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("WalletIdentifierId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AssetWalletId");

                    b.HasIndex("ExcelId");

                    b.HasIndex("TagId");

                    b.HasIndex("WalletIdentifierId");

                    b.ToTable("DigitalAssetTransactions");
                });

            modelBuilder.Entity("SFManagement.Models.Transactions.Excel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DeleteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("EditorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FileName")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("FileType")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<Guid>("PokerManagerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PokerManagerId");

                    b.ToTable("Excels");
                });

            modelBuilder.Entity("SFManagement.Models.Transactions.ExcelTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Coins")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeleteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("DigitalAssetTransactionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("EditorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ExcelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ExcelNickname")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("ExcelWallet")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("TransactionDirection")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DigitalAssetTransactionId");

                    b.HasIndex("ExcelId");

                    b.ToTable("ExcelTransactions");
                });

            modelBuilder.Entity("SFManagement.Models.Transactions.FiatAssetTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ApprovedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AssetAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("AssetWalletId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeleteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("EditorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OfxTransactionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TagId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TransactionDirection")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("WalletIdentifierId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AssetWalletId");

                    b.HasIndex("OfxTransactionId");

                    b.HasIndex("TagId");

                    b.HasIndex("WalletIdentifierId");

                    b.ToTable("FiatAssetTransactions");
                });

            modelBuilder.Entity("SFManagement.Models.Transactions.InternalTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ApprovedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssetWalletId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BankId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ClosingManagerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Coins")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeleteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("EditorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("ExchangeRate")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("InternalTransactionType")
                        .HasColumnType("int");

                    b.Property<bool>("IsProfit")
                        .HasColumnType("bit");

                    b.Property<Guid?>("TagId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TransferId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Value")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("WalletIdentifierId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AssetWalletId");

                    b.HasIndex("BankId");

                    b.HasIndex("ClosingManagerId");

                    b.HasIndex("TagId");

                    b.HasIndex("WalletIdentifierId");

                    b.ToTable("InternalTransactions");
                });

            modelBuilder.Entity("SFManagement.Models.Transactions.Ofx", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BankId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DeleteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("EditorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BankId");

                    b.ToTable("Ofxs");
                });

            modelBuilder.Entity("SFManagement.Models.Transactions.OfxTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeleteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<Guid?>("EditorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FitId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<Guid>("OfxId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TransactionDirection")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Value")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OfxId");

                    b.ToTable("OfxTransactions");
                });

            modelBuilder.Entity("SFManagement.Models.Entities.Bank", b =>
                {
                    b.HasBaseType("SFManagement.Models.Entities.BaseAssetHolder");

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.ToTable("Banks");
                });

            modelBuilder.Entity("SFManagement.Models.Entities.Client", b =>
                {
                    b.HasBaseType("SFManagement.Models.Entities.BaseAssetHolder");

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("datetime2");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("SFManagement.Models.Entities.Member", b =>
                {
                    b.HasBaseType("SFManagement.Models.Entities.BaseAssetHolder");

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<double>("Share")
                        .HasColumnType("float");

                    b.ToTable("Member");
                });

            modelBuilder.Entity("SFManagement.Models.Entities.PokerManager", b =>
                {
                    b.HasBaseType("SFManagement.Models.Entities.BaseAssetHolder");

                    b.ToTable("PokerManagers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("SFManagement.Models.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("SFManagement.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("SFManagement.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("SFManagement.Models.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SFManagement.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("SFManagement.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SFManagement.Models.Closing.ClosingNickname", b =>
                {
                    b.HasOne("SFManagement.Models.Closing.ClosingManager", "ClosingManager")
                        .WithMany("ClosingNicknames")
                        .HasForeignKey("ClosingManagerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClosingManager");
                });

            modelBuilder.Entity("SFManagement.Models.Closing.ClosingWallet", b =>
                {
                    b.HasOne("SFManagement.Models.Entities.AssetWallet", "AssetWallet")
                        .WithMany()
                        .HasForeignKey("AssetWalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SFManagement.Models.Closing.ClosingManager", "ClosingManager")
                        .WithMany("ClosingWallets")
                        .HasForeignKey("ClosingManagerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssetWallet");

                    b.Navigation("ClosingManager");
                });

            modelBuilder.Entity("SFManagement.Models.Entities.Address", b =>
                {
                    b.HasOne("SFManagement.Models.Entities.Bank", "Bank")
                        .WithOne("Address")
                        .HasForeignKey("SFManagement.Models.Entities.Address", "BankId");

                    b.HasOne("SFManagement.Models.Entities.Client", "Client")
                        .WithOne("Address")
                        .HasForeignKey("SFManagement.Models.Entities.Address", "ClientId");

                    b.HasOne("SFManagement.Models.Entities.Member", "Member")
                        .WithOne("Address")
                        .HasForeignKey("SFManagement.Models.Entities.Address", "MemberId");

                    b.HasOne("SFManagement.Models.Entities.PokerManager", "PokerManager")
                        .WithOne("Address")
                        .HasForeignKey("SFManagement.Models.Entities.Address", "PokerManagerId");

                    b.Navigation("Bank");

                    b.Navigation("Client");

                    b.Navigation("Member");

                    b.Navigation("PokerManager");
                });

            modelBuilder.Entity("SFManagement.Models.Entities.AssetWallet", b =>
                {
                    b.HasOne("SFManagement.Models.Entities.Bank", "Bank")
                        .WithMany("AssetWallets")
                        .HasForeignKey("BankId");

                    b.HasOne("SFManagement.Models.Entities.Client", "Client")
                        .WithMany("AssetWallets")
                        .HasForeignKey("ClientId");

                    b.HasOne("SFManagement.Models.Entities.Member", "Member")
                        .WithMany("AssetWallets")
                        .HasForeignKey("MemberId");

                    b.HasOne("SFManagement.Models.Entities.PokerManager", "PokerManager")
                        .WithMany("AssetWallets")
                        .HasForeignKey("PokerManagerId");

                    b.Navigation("Bank");

                    b.Navigation("Client");

                    b.Navigation("Member");

                    b.Navigation("PokerManager");
                });

            modelBuilder.Entity("SFManagement.Models.Entities.ContactPhone", b =>
                {
                    b.HasOne("SFManagement.Models.Entities.Bank", "Bank")
                        .WithMany("ContactPhones")
                        .HasForeignKey("BankId");

                    b.HasOne("SFManagement.Models.Entities.Client", "Client")
                        .WithMany("ContactPhones")
                        .HasForeignKey("ClientId");

                    b.HasOne("SFManagement.Models.Entities.Member", "Member")
                        .WithMany("PhonesNumbers")
                        .HasForeignKey("MemberId");

                    b.HasOne("SFManagement.Models.Entities.PokerManager", "PokerManager")
                        .WithMany("PhonesNumbers")
                        .HasForeignKey("PokerManagerId");

                    b.Navigation("Bank");

                    b.Navigation("Client");

                    b.Navigation("Member");

                    b.Navigation("PokerManager");
                });

            modelBuilder.Entity("SFManagement.Models.Entities.InitialBalance", b =>
                {
                    b.HasOne("SFManagement.Models.Entities.Bank", "Bank")
                        .WithMany("InitialBalances")
                        .HasForeignKey("BankId");

                    b.HasOne("SFManagement.Models.Entities.Client", "Client")
                        .WithMany("InitialBalances")
                        .HasForeignKey("ClientId");

                    b.HasOne("SFManagement.Models.Entities.Member", "Member")
                        .WithMany("InitialBalances")
                        .HasForeignKey("MemberId");

                    b.HasOne("SFManagement.Models.Entities.PokerManager", "PokerManager")
                        .WithMany("InitialBalances")
                        .HasForeignKey("PokerManagerId");

                    b.Navigation("Bank");

                    b.Navigation("Client");

                    b.Navigation("Member");

                    b.Navigation("PokerManager");
                });

            modelBuilder.Entity("SFManagement.Models.Entities.WalletIdentifier", b =>
                {
                    b.HasOne("SFManagement.Models.Entities.AssetWallet", null)
                        .WithMany("WalletIdentifiers")
                        .HasForeignKey("AssetWalletId");

                    b.HasOne("SFManagement.Models.Entities.Bank", "Bank")
                        .WithMany()
                        .HasForeignKey("BankId");

                    b.HasOne("SFManagement.Models.Entities.Client", "Client")
                        .WithMany("WalletIdentifiers")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SFManagement.Models.Entities.Member", "Member")
                        .WithMany("WalletIdentifiers")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SFManagement.Models.Entities.PokerManager", "PokerManager")
                        .WithMany("WalletIdentifiers")
                        .HasForeignKey("PokerManagerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Bank");

                    b.Navigation("Client");

                    b.Navigation("Member");

                    b.Navigation("PokerManager");
                });

            modelBuilder.Entity("SFManagement.Models.Tag", b =>
                {
                    b.HasOne("SFManagement.Models.Tag", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("SFManagement.Models.Transactions.DigitalAssetTransaction", b =>
                {
                    b.HasOne("SFManagement.Models.Entities.AssetWallet", "AssetWallet")
                        .WithMany()
                        .HasForeignKey("AssetWalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SFManagement.Models.Transactions.Excel", "Excel")
                        .WithMany()
                        .HasForeignKey("ExcelId");

                    b.HasOne("SFManagement.Models.Tag", "Tag")
                        .WithMany("WalletTransactions")
                        .HasForeignKey("TagId");

                    b.HasOne("SFManagement.Models.Entities.WalletIdentifier", "WalletIdentifier")
                        .WithMany()
                        .HasForeignKey("WalletIdentifierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssetWallet");

                    b.Navigation("Excel");

                    b.Navigation("Tag");

                    b.Navigation("WalletIdentifier");
                });

            modelBuilder.Entity("SFManagement.Models.Transactions.Excel", b =>
                {
                    b.HasOne("SFManagement.Models.Entities.PokerManager", "PokerManager")
                        .WithMany("Excels")
                        .HasForeignKey("PokerManagerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PokerManager");
                });

            modelBuilder.Entity("SFManagement.Models.Transactions.ExcelTransaction", b =>
                {
                    b.HasOne("SFManagement.Models.Transactions.DigitalAssetTransaction", "DigitalAssetTransaction")
                        .WithMany()
                        .HasForeignKey("DigitalAssetTransactionId");

                    b.HasOne("SFManagement.Models.Transactions.Excel", "Excel")
                        .WithMany("ExcelTransactions")
                        .HasForeignKey("ExcelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DigitalAssetTransaction");

                    b.Navigation("Excel");
                });

            modelBuilder.Entity("SFManagement.Models.Transactions.FiatAssetTransaction", b =>
                {
                    b.HasOne("SFManagement.Models.Entities.AssetWallet", "AssetWallet")
                        .WithMany()
                        .HasForeignKey("AssetWalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SFManagement.Models.Transactions.OfxTransaction", "OfxTransaction")
                        .WithMany()
                        .HasForeignKey("OfxTransactionId");

                    b.HasOne("SFManagement.Models.Tag", "Tag")
                        .WithMany("BankTransactions")
                        .HasForeignKey("TagId");

                    b.HasOne("SFManagement.Models.Entities.WalletIdentifier", "WalletIdentifier")
                        .WithMany()
                        .HasForeignKey("WalletIdentifierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssetWallet");

                    b.Navigation("OfxTransaction");

                    b.Navigation("Tag");

                    b.Navigation("WalletIdentifier");
                });

            modelBuilder.Entity("SFManagement.Models.Transactions.InternalTransaction", b =>
                {
                    b.HasOne("SFManagement.Models.Entities.AssetWallet", "AssetWallet")
                        .WithMany()
                        .HasForeignKey("AssetWalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SFManagement.Models.Entities.Bank", "Bank")
                        .WithMany()
                        .HasForeignKey("BankId");

                    b.HasOne("SFManagement.Models.Closing.ClosingManager", "ClosingManager")
                        .WithMany("InternalTransactions")
                        .HasForeignKey("ClosingManagerId");

                    b.HasOne("SFManagement.Models.Tag", "Tag")
                        .WithMany("InternalTransactions")
                        .HasForeignKey("TagId");

                    b.HasOne("SFManagement.Models.Entities.WalletIdentifier", "WalletIdentifier")
                        .WithMany()
                        .HasForeignKey("WalletIdentifierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssetWallet");

                    b.Navigation("Bank");

                    b.Navigation("ClosingManager");

                    b.Navigation("Tag");

                    b.Navigation("WalletIdentifier");
                });

            modelBuilder.Entity("SFManagement.Models.Transactions.Ofx", b =>
                {
                    b.HasOne("SFManagement.Models.Entities.Bank", "Bank")
                        .WithMany("Ofxs")
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bank");
                });

            modelBuilder.Entity("SFManagement.Models.Transactions.OfxTransaction", b =>
                {
                    b.HasOne("SFManagement.Models.Transactions.Ofx", "Ofx")
                        .WithMany("OfxTransactions")
                        .HasForeignKey("OfxId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ofx");
                });

            modelBuilder.Entity("SFManagement.Models.Closing.ClosingManager", b =>
                {
                    b.Navigation("ClosingNicknames");

                    b.Navigation("ClosingWallets");

                    b.Navigation("InternalTransactions");
                });

            modelBuilder.Entity("SFManagement.Models.Entities.AssetWallet", b =>
                {
                    b.Navigation("WalletIdentifiers");
                });

            modelBuilder.Entity("SFManagement.Models.Tag", b =>
                {
                    b.Navigation("BankTransactions");

                    b.Navigation("Children");

                    b.Navigation("InternalTransactions");

                    b.Navigation("WalletTransactions");
                });

            modelBuilder.Entity("SFManagement.Models.Transactions.Excel", b =>
                {
                    b.Navigation("ExcelTransactions");
                });

            modelBuilder.Entity("SFManagement.Models.Transactions.Ofx", b =>
                {
                    b.Navigation("OfxTransactions");
                });

            modelBuilder.Entity("SFManagement.Models.Entities.Bank", b =>
                {
                    b.Navigation("Address");

                    b.Navigation("AssetWallets");

                    b.Navigation("ContactPhones");

                    b.Navigation("InitialBalances");

                    b.Navigation("Ofxs");
                });

            modelBuilder.Entity("SFManagement.Models.Entities.Client", b =>
                {
                    b.Navigation("Address");

                    b.Navigation("AssetWallets");

                    b.Navigation("ContactPhones");

                    b.Navigation("InitialBalances");

                    b.Navigation("WalletIdentifiers");
                });

            modelBuilder.Entity("SFManagement.Models.Entities.Member", b =>
                {
                    b.Navigation("Address");

                    b.Navigation("AssetWallets");

                    b.Navigation("InitialBalances");

                    b.Navigation("PhonesNumbers");

                    b.Navigation("WalletIdentifiers");
                });

            modelBuilder.Entity("SFManagement.Models.Entities.PokerManager", b =>
                {
                    b.Navigation("Address");

                    b.Navigation("AssetWallets");

                    b.Navigation("Excels");

                    b.Navigation("InitialBalances");

                    b.Navigation("PhonesNumbers");

                    b.Navigation("WalletIdentifiers");
                });
#pragma warning restore 612, 618
        }
    }
}
