// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SFManagement.Data;

#nullable disable

namespace SFManagement.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250709231309_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SFManagement.Models.AssetInfrastructure.AssetWallet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AssetType")
                        .HasColumnType("int");

                    b.Property<Guid>("BaseAssetHolderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AssetType")
                        .HasDatabaseName("IX_AssetWallet_AssetType");

                    b.HasIndex("BaseAssetHolderId")
                        .HasDatabaseName("IX_AssetWallet_BaseAssetHolderId");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("IX_AssetWallet_DeletedAt");

                    b.HasIndex("BaseAssetHolderId", "AssetType")
                        .HasDatabaseName("IX_AssetWallet_BaseAssetHolder_AssetType");

                    b.ToTable("AssetWallets");
                });

            modelBuilder.Entity("SFManagement.Models.AssetInfrastructure.WalletIdentifier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssetWalletId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("WalletType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssetWalletId")
                        .HasDatabaseName("IX_WalletIdentifier_AssetWalletId");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("IX_WalletIdentifier_DeletedAt");

                    b.ToTable("WalletIdentifiers");
                });

            modelBuilder.Entity("SFManagement.Models.Entities.Bank", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BaseAssetHolderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BaseAssetHolderId")
                        .IsUnique()
                        .HasDatabaseName("IX_Bank_BaseAssetHolderId");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_Bank_Code_Active")
                        .HasFilter("[DeletedAt] IS NULL");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("IX_Bank_DeletedAt");

                    b.ToTable("Banks");
                });

            modelBuilder.Entity("SFManagement.Models.Entities.BaseAssetHolder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cnpj")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Cpf")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<Guid>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Cnpj")
                        .IsUnique()
                        .HasDatabaseName("UQ_BaseAssetHolder_Cnpj")
                        .HasFilter("[Cnpj] IS NOT NULL");

                    b.HasIndex("Cpf")
                        .IsUnique()
                        .HasDatabaseName("UQ_BaseAssetHolder_Cpf")
                        .HasFilter("[Cpf] IS NOT NULL");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("IX_BaseAssetHolder_DeletedAt");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UQ_BaseAssetHolder_Email")
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_BaseAssetHolder_Name");

                    b.ToTable("BaseAssetHolders");
                });

            modelBuilder.Entity("SFManagement.Models.Entities.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BaseAssetHolderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BaseAssetHolderId")
                        .IsUnique()
                        .HasDatabaseName("IX_Client_BaseAssetHolderId");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("IX_Client_DeletedAt");

                    b.ToTable("Clients", t =>
                        {
                            t.HasCheckConstraint("CK_Client_Birthday_NotFuture", "[Birthday] IS NULL OR [Birthday] <= GETDATE()");
                        });
                });

            modelBuilder.Entity("SFManagement.Models.Entities.Member", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BaseAssetHolderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Share")
                        .HasPrecision(5, 4)
                        .HasColumnType("float(5)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BaseAssetHolderId")
                        .IsUnique()
                        .HasDatabaseName("IX_Member_BaseAssetHolderId");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("IX_Member_DeletedAt");

                    b.ToTable("Members", t =>
                        {
                            t.HasCheckConstraint("CK_Member_Birthday_NotFuture", "[Birthday] IS NULL OR [Birthday] <= GETDATE()");

                            t.HasCheckConstraint("CK_Member_Share_Range", "[Share] >= 0 AND [Share] <= 1");
                        });
                });

            modelBuilder.Entity("SFManagement.Models.Entities.PokerManager", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BaseAssetHolderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BaseAssetHolderId")
                        .IsUnique()
                        .HasDatabaseName("IX_PokerManager_BaseAssetHolderId");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("IX_PokerManager_DeletedAt");

                    b.ToTable("PokerManagers");
                });

            modelBuilder.Entity("SFManagement.Models.Support.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BaseAssetHolderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Complement")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Country")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Postcode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("State")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("StreetAddress")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BaseAssetHolderId")
                        .IsUnique();

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("SFManagement.Models.Support.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FinancialBehavior")
                        .HasColumnType("int");

                    b.Property<Guid>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("SFManagement.Models.Support.ContactPhone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BaseAssetHolderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("CountryCode")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("LocalCode")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SearchFor")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BaseAssetHolderId");

                    b.ToTable("ContactPhone");
                });

            modelBuilder.Entity("SFManagement.Models.Support.InitialBalance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Balance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("BalanceAs")
                        .HasColumnType("int");

                    b.Property<int>("BalanceUnit")
                        .HasColumnType("int");

                    b.Property<Guid>("BaseAssetHolderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("ConversionRate")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BaseAssetHolderId");

                    b.ToTable("InitialBalances");
                });

            modelBuilder.Entity("SFManagement.Models.Support.Referral", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ActiveUntil")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<Guid>("AssetHolderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("ParentCommission")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("WalletIdentifierId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AssetHolderId");

                    b.HasIndex("WalletIdentifierId")
                        .IsUnique();

                    b.ToTable("Referral");
                });

            modelBuilder.Entity("SFManagement.Models.Transactions.DigitalAssetTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("AssetAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("BalanceAs")
                        .HasColumnType("int");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("ConversionRate")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("ExcelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Rate")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ReceiverWalletIdentifierId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SenderWalletIdentifierId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Date")
                        .HasDatabaseName("IX_DigitalAssetTransaction_Date");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("IX_DigitalAssetTransaction_DeletedAt");

                    b.HasIndex("ExcelId");

                    b.HasIndex("ReceiverWalletIdentifierId", "Date")
                        .HasDatabaseName("IX_DigitalAssetTransaction_Receiver_Date");

                    b.HasIndex("SenderWalletIdentifierId", "Date")
                        .HasDatabaseName("IX_DigitalAssetTransaction_Sender_Date");

                    b.ToTable("DigitalAssetTransactions", t =>
                        {
                            t.HasCheckConstraint("CK_DigitalAssetTransaction_AssetAmount_Positive", "[AssetAmount] > 0");

                            t.HasCheckConstraint("CK_DigitalAssetTransaction_Date_NotFuture", "[Date] <= GETDATE()");

                            t.HasCheckConstraint("CK_DigitalAssetTransaction_Different_Sender_Receiver", "[SenderWalletIdentifierId] <> [ReceiverWalletIdentifierId]");
                        });
                });

            modelBuilder.Entity("SFManagement.Models.Transactions.Excel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("FileType")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<Guid>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PokerManagerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PokerManagerId");

                    b.ToTable("Excels");
                });

            modelBuilder.Entity("SFManagement.Models.Transactions.ExcelTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Coins")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("DigitalAssetTransactionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ExcelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ExcelNickname")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("ExcelWallet")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<Guid>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TransactionDirection")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DigitalAssetTransactionId");

                    b.HasIndex("ExcelId");

                    b.ToTable("ExcelTransactions");
                });

            modelBuilder.Entity("SFManagement.Models.Transactions.FiatAssetTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("AssetAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OfxTransactionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ReceiverWalletIdentifierId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SenderWalletIdentifierId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Date")
                        .HasDatabaseName("IX_FiatAssetTransaction_Date");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("IX_FiatAssetTransaction_DeletedAt");

                    b.HasIndex("OfxTransactionId");

                    b.HasIndex("ReceiverWalletIdentifierId", "Date")
                        .HasDatabaseName("IX_FiatAssetTransaction_Receiver_Date");

                    b.HasIndex("SenderWalletIdentifierId", "Date")
                        .HasDatabaseName("IX_FiatAssetTransaction_Sender_Date");

                    b.ToTable("FiatAssetTransactions", t =>
                        {
                            t.HasCheckConstraint("CK_FiatAssetTransaction_AssetAmount_Positive", "[AssetAmount] > 0");

                            t.HasCheckConstraint("CK_FiatAssetTransaction_Date_NotFuture", "[Date] <= GETDATE()");

                            t.HasCheckConstraint("CK_FiatAssetTransaction_Different_Sender_Receiver", "[SenderWalletIdentifierId] <> [ReceiverWalletIdentifierId]");
                        });
                });

            modelBuilder.Entity("SFManagement.Models.Transactions.Ofx", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BankId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<Guid>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BankId");

                    b.ToTable("Ofxs");
                });

            modelBuilder.Entity("SFManagement.Models.Transactions.OfxTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("FitId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<Guid>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OfxId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TransactionDirection")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Value")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OfxId");

                    b.ToTable("OfxTransactions");
                });

            modelBuilder.Entity("SFManagement.Models.Transactions.SettlementTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("AssetAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Rake")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("RakeBack")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RakeCommission")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ReceiverWalletIdentifierId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SenderWalletIdentifierId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Date")
                        .HasDatabaseName("IX_SettlementTransaction_Date");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("IX_SettlementTransaction_DeletedAt");

                    b.HasIndex("ReceiverWalletIdentifierId", "Date")
                        .HasDatabaseName("IX_SettlementTransaction_Receiver_Date");

                    b.HasIndex("SenderWalletIdentifierId", "Date")
                        .HasDatabaseName("IX_SettlementTransaction_Sender_Date");

                    b.ToTable("SettlementTransactions", t =>
                        {
                            t.HasCheckConstraint("CK_SettlementTransaction_AssetAmount_Positive", "[AssetAmount] > 0");

                            t.HasCheckConstraint("CK_SettlementTransaction_Date_NotFuture", "[Date] <= GETDATE()");

                            t.HasCheckConstraint("CK_SettlementTransaction_Different_Sender_Receiver", "[SenderWalletIdentifierId] <> [ReceiverWalletIdentifierId]");
                        });
                });

            modelBuilder.Entity("SFManagement.Models.AssetInfrastructure.AssetWallet", b =>
                {
                    b.HasOne("SFManagement.Models.Entities.BaseAssetHolder", "BaseAssetHolder")
                        .WithMany("AssetWallets")
                        .HasForeignKey("BaseAssetHolderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BaseAssetHolder");
                });

            modelBuilder.Entity("SFManagement.Models.AssetInfrastructure.WalletIdentifier", b =>
                {
                    b.HasOne("SFManagement.Models.AssetInfrastructure.AssetWallet", "AssetWallet")
                        .WithMany("WalletIdentifiers")
                        .HasForeignKey("AssetWalletId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssetWallet");
                });

            modelBuilder.Entity("SFManagement.Models.Entities.Bank", b =>
                {
                    b.HasOne("SFManagement.Models.Entities.BaseAssetHolder", "BaseAssetHolder")
                        .WithOne("Bank")
                        .HasForeignKey("SFManagement.Models.Entities.Bank", "BaseAssetHolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaseAssetHolder");
                });

            modelBuilder.Entity("SFManagement.Models.Entities.Client", b =>
                {
                    b.HasOne("SFManagement.Models.Entities.BaseAssetHolder", "BaseAssetHolder")
                        .WithOne("Client")
                        .HasForeignKey("SFManagement.Models.Entities.Client", "BaseAssetHolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaseAssetHolder");
                });

            modelBuilder.Entity("SFManagement.Models.Entities.Member", b =>
                {
                    b.HasOne("SFManagement.Models.Entities.BaseAssetHolder", "BaseAssetHolder")
                        .WithOne("Member")
                        .HasForeignKey("SFManagement.Models.Entities.Member", "BaseAssetHolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaseAssetHolder");
                });

            modelBuilder.Entity("SFManagement.Models.Entities.PokerManager", b =>
                {
                    b.HasOne("SFManagement.Models.Entities.BaseAssetHolder", "BaseAssetHolder")
                        .WithOne("PokerManager")
                        .HasForeignKey("SFManagement.Models.Entities.PokerManager", "BaseAssetHolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaseAssetHolder");
                });

            modelBuilder.Entity("SFManagement.Models.Support.Address", b =>
                {
                    b.HasOne("SFManagement.Models.Entities.BaseAssetHolder", null)
                        .WithOne("Address")
                        .HasForeignKey("SFManagement.Models.Support.Address", "BaseAssetHolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SFManagement.Models.Support.Category", b =>
                {
                    b.HasOne("SFManagement.Models.Support.Category", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("SFManagement.Models.Support.ContactPhone", b =>
                {
                    b.HasOne("SFManagement.Models.Entities.BaseAssetHolder", null)
                        .WithMany("ContactPhones")
                        .HasForeignKey("BaseAssetHolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SFManagement.Models.Support.InitialBalance", b =>
                {
                    b.HasOne("SFManagement.Models.Entities.BaseAssetHolder", null)
                        .WithMany("InitialBalances")
                        .HasForeignKey("BaseAssetHolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SFManagement.Models.Support.Referral", b =>
                {
                    b.HasOne("SFManagement.Models.Entities.BaseAssetHolder", "AssetHolder")
                        .WithMany("Referral")
                        .HasForeignKey("AssetHolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SFManagement.Models.AssetInfrastructure.WalletIdentifier", "WalletIdentifier")
                        .WithOne("Referral")
                        .HasForeignKey("SFManagement.Models.Support.Referral", "WalletIdentifierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssetHolder");

                    b.Navigation("WalletIdentifier");
                });

            modelBuilder.Entity("SFManagement.Models.Transactions.DigitalAssetTransaction", b =>
                {
                    b.HasOne("SFManagement.Models.Support.Category", "Category")
                        .WithMany("WalletTransactions")
                        .HasForeignKey("CategoryId");

                    b.HasOne("SFManagement.Models.Transactions.Excel", "Excel")
                        .WithMany()
                        .HasForeignKey("ExcelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SFManagement.Models.AssetInfrastructure.WalletIdentifier", "ReceiverWalletIdentifier")
                        .WithMany()
                        .HasForeignKey("ReceiverWalletIdentifierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SFManagement.Models.AssetInfrastructure.WalletIdentifier", "SenderWalletIdentifier")
                        .WithMany()
                        .HasForeignKey("SenderWalletIdentifierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Excel");

                    b.Navigation("ReceiverWalletIdentifier");

                    b.Navigation("SenderWalletIdentifier");
                });

            modelBuilder.Entity("SFManagement.Models.Transactions.Excel", b =>
                {
                    b.HasOne("SFManagement.Models.Entities.PokerManager", "PokerManager")
                        .WithMany("Excels")
                        .HasForeignKey("PokerManagerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PokerManager");
                });

            modelBuilder.Entity("SFManagement.Models.Transactions.ExcelTransaction", b =>
                {
                    b.HasOne("SFManagement.Models.Transactions.DigitalAssetTransaction", "DigitalAssetTransaction")
                        .WithMany()
                        .HasForeignKey("DigitalAssetTransactionId");

                    b.HasOne("SFManagement.Models.Transactions.Excel", "Excel")
                        .WithMany("ExcelTransactions")
                        .HasForeignKey("ExcelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DigitalAssetTransaction");

                    b.Navigation("Excel");
                });

            modelBuilder.Entity("SFManagement.Models.Transactions.FiatAssetTransaction", b =>
                {
                    b.HasOne("SFManagement.Models.Support.Category", "Category")
                        .WithMany("BankTransactions")
                        .HasForeignKey("CategoryId");

                    b.HasOne("SFManagement.Models.Transactions.OfxTransaction", "OfxTransaction")
                        .WithMany()
                        .HasForeignKey("OfxTransactionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SFManagement.Models.AssetInfrastructure.WalletIdentifier", "ReceiverWalletIdentifier")
                        .WithMany()
                        .HasForeignKey("ReceiverWalletIdentifierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SFManagement.Models.AssetInfrastructure.WalletIdentifier", "SenderWalletIdentifier")
                        .WithMany()
                        .HasForeignKey("SenderWalletIdentifierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("OfxTransaction");

                    b.Navigation("ReceiverWalletIdentifier");

                    b.Navigation("SenderWalletIdentifier");
                });

            modelBuilder.Entity("SFManagement.Models.Transactions.Ofx", b =>
                {
                    b.HasOne("SFManagement.Models.Entities.Bank", "Bank")
                        .WithMany("Ofxs")
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bank");
                });

            modelBuilder.Entity("SFManagement.Models.Transactions.OfxTransaction", b =>
                {
                    b.HasOne("SFManagement.Models.Transactions.Ofx", "Ofx")
                        .WithMany("OfxTransactions")
                        .HasForeignKey("OfxId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ofx");
                });

            modelBuilder.Entity("SFManagement.Models.Transactions.SettlementTransaction", b =>
                {
                    b.HasOne("SFManagement.Models.Support.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.HasOne("SFManagement.Models.AssetInfrastructure.WalletIdentifier", "ReceiverWalletIdentifier")
                        .WithMany()
                        .HasForeignKey("ReceiverWalletIdentifierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SFManagement.Models.AssetInfrastructure.WalletIdentifier", "SenderWalletIdentifier")
                        .WithMany()
                        .HasForeignKey("SenderWalletIdentifierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("ReceiverWalletIdentifier");

                    b.Navigation("SenderWalletIdentifier");
                });

            modelBuilder.Entity("SFManagement.Models.AssetInfrastructure.AssetWallet", b =>
                {
                    b.Navigation("WalletIdentifiers");
                });

            modelBuilder.Entity("SFManagement.Models.AssetInfrastructure.WalletIdentifier", b =>
                {
                    b.Navigation("Referral");
                });

            modelBuilder.Entity("SFManagement.Models.Entities.Bank", b =>
                {
                    b.Navigation("Ofxs");
                });

            modelBuilder.Entity("SFManagement.Models.Entities.BaseAssetHolder", b =>
                {
                    b.Navigation("Address");

                    b.Navigation("AssetWallets");

                    b.Navigation("Bank");

                    b.Navigation("Client");

                    b.Navigation("ContactPhones");

                    b.Navigation("InitialBalances");

                    b.Navigation("Member");

                    b.Navigation("PokerManager");

                    b.Navigation("Referral");
                });

            modelBuilder.Entity("SFManagement.Models.Entities.PokerManager", b =>
                {
                    b.Navigation("Excels");
                });

            modelBuilder.Entity("SFManagement.Models.Support.Category", b =>
                {
                    b.Navigation("BankTransactions");

                    b.Navigation("Children");

                    b.Navigation("WalletTransactions");
                });

            modelBuilder.Entity("SFManagement.Models.Transactions.Excel", b =>
                {
                    b.Navigation("ExcelTransactions");
                });

            modelBuilder.Entity("SFManagement.Models.Transactions.Ofx", b =>
                {
                    b.Navigation("OfxTransactions");
                });
#pragma warning restore 612, 618
        }
    }
}
