// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SFManagement.Data;

#nullable disable

namespace SFManagement.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SFManagement.Models.AssetInfrastructure.AssetPool", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AssetGroup")
                        .HasColumnType("int");

                    b.Property<Guid?>("BaseAssetHolderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AssetGroup")
                        .HasDatabaseName("IX_AssetPool_AssetGroup");

                    b.HasIndex("BaseAssetHolderId")
                        .HasDatabaseName("IX_AssetPool_BaseAssetHolderId");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("IX_AssetPool_DeletedAt");

                    b.HasIndex("BaseAssetHolderId", "AssetGroup")
                        .HasDatabaseName("IX_AssetPool_BaseAssetHolder_AssetGroup");

                    b.ToTable("AssetPools");
                });

            modelBuilder.Entity("SFManagement.Models.AssetInfrastructure.WalletIdentifier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccountClassification")
                        .HasColumnType("int");

                    b.Property<Guid>("AssetPoolId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AssetType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AssetPoolId")
                        .HasDatabaseName("IX_WalletIdentifier_AssetPoolId");

                    b.HasIndex("AssetType")
                        .HasDatabaseName("IX_WalletIdentifier_AssetType");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("IX_WalletIdentifier_DeletedAt");

                    b.ToTable("WalletIdentifiers");
                });

            modelBuilder.Entity("SFManagement.Models.Entities.Bank", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BaseAssetHolderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BaseAssetHolderId")
                        .IsUnique()
                        .HasDatabaseName("IX_Bank_BaseAssetHolderId");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_Bank_Code_Active")
                        .HasFilter("[DeletedAt] IS NULL");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("IX_Bank_DeletedAt");

                    b.ToTable("Banks");
                });

            modelBuilder.Entity("SFManagement.Models.Entities.BaseAssetHolder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cnpj")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Cpf")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<Guid?>("ReferrerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Cnpj")
                        .IsUnique()
                        .HasDatabaseName("UQ_BaseAssetHolder_Cnpj")
                        .HasFilter("[Cnpj] IS NOT NULL");

                    b.HasIndex("Cpf")
                        .IsUnique()
                        .HasDatabaseName("UQ_BaseAssetHolder_Cpf")
                        .HasFilter("[Cpf] IS NOT NULL");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("IX_BaseAssetHolder_DeletedAt");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_BaseAssetHolder_Name");

                    b.HasIndex("ReferrerId")
                        .HasDatabaseName("IX_BaseAssetHolder_ReferrerId");

                    b.ToTable("BaseAssetHolders");
                });

            modelBuilder.Entity("SFManagement.Models.Entities.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BaseAssetHolderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BaseAssetHolderId")
                        .IsUnique()
                        .HasDatabaseName("IX_Client_BaseAssetHolderId");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("IX_Client_DeletedAt");

                    b.ToTable("Clients", t =>
                        {
                            t.HasCheckConstraint("CK_Client_Birthday_NotFuture", "[Birthday] IS NULL OR [Birthday] <= GETDATE()");
                        });
                });

            modelBuilder.Entity("SFManagement.Models.Entities.Member", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BaseAssetHolderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Share")
                        .HasPrecision(5, 4)
                        .HasColumnType("float(5)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BaseAssetHolderId")
                        .IsUnique()
                        .HasDatabaseName("IX_Member_BaseAssetHolderId");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("IX_Member_DeletedAt");

                    b.ToTable("Members", t =>
                        {
                            t.HasCheckConstraint("CK_Member_Birthday_NotFuture", "[Birthday] IS NULL OR [Birthday] <= GETDATE()");

                            t.HasCheckConstraint("CK_Member_Share_Range", "[Share] >= 0 AND [Share] <= 1");
                        });
                });

            modelBuilder.Entity("SFManagement.Models.Entities.PokerManager", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BaseAssetHolderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("ManagerType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BaseAssetHolderId")
                        .IsUnique()
                        .HasDatabaseName("IX_PokerManager_BaseAssetHolderId");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("IX_PokerManager_DeletedAt");

                    b.ToTable("PokerManagers");
                });

            modelBuilder.Entity("SFManagement.Models.Support.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BaseAssetHolderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Postcode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BaseAssetHolderId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("SFManagement.Models.Support.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("SFManagement.Models.Support.ContactPhone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("AreaCode")
                        .HasColumnType("int");

                    b.Property<Guid>("BaseAssetHolderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("CountryCode")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("InputPhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("PhoneNumber")
                        .HasColumnType("int");

                    b.Property<string>("SearchFor")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BaseAssetHolderId");

                    b.ToTable("ContactPhone");
                });

            modelBuilder.Entity("SFManagement.Models.Support.InitialBalance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AssetGroup")
                        .HasColumnType("int");

                    b.Property<int>("AssetType")
                        .HasColumnType("int");

                    b.Property<decimal>("Balance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("BalanceAs")
                        .HasColumnType("int");

                    b.Property<Guid>("BaseAssetHolderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("ConversionRate")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BaseAssetHolderId")
                        .HasDatabaseName("IX_InitialBalance_BaseAssetHolderId");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("IX_InitialBalance_DeletedAt");

                    b.HasIndex("BaseAssetHolderId", "AssetGroup")
                        .HasDatabaseName("IX_InitialBalance_BaseAssetHolder_AssetGroup");

                    b.HasIndex("BaseAssetHolderId", "AssetType")
                        .HasDatabaseName("IX_InitialBalance_BaseAssetHolder_AssetType");

                    b.ToTable("InitialBalances", t =>
                        {
                            t.HasCheckConstraint("CK_InitialBalance_AssetType_AssetGroup_Exclusive", "([AssetType] = 0 AND [AssetGroup] <> 0) OR ([AssetType] <> 0 AND [AssetGroup] = 0)");

                            t.HasCheckConstraint("CK_InitialBalance_AssetType_Or_AssetGroup_Required", "[AssetType] <> 0 OR [AssetGroup] <> 0");

                            t.HasCheckConstraint("CK_InitialBalance_ConversionRate_Positive", "[ConversionRate] IS NULL OR [ConversionRate] > 0");
                        });
                });

            modelBuilder.Entity("SFManagement.Models.Support.Referral", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ActiveFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ActiveUntil")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("AssetHolderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BaseAssetHolderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("ParentCommission")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("WalletIdentifierId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AssetHolderId")
                        .HasDatabaseName("IX_Referral_AssetHolderId");

                    b.HasIndex("BaseAssetHolderId");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("IX_Referral_DeletedAt");

                    b.HasIndex("WalletIdentifierId")
                        .HasDatabaseName("IX_Referral_WalletIdentifierId");

                    b.HasIndex("WalletIdentifierId", "ActiveFrom", "ActiveUntil")
                        .HasDatabaseName("IX_Referral_Wallet_ActivePeriod");

                    b.ToTable("Referrals", t =>
                        {
                            t.HasCheckConstraint("CK_Referral_ActiveDates_Logical", "[ActiveFrom] IS NULL OR [ActiveUntil] IS NULL OR [ActiveFrom] <= [ActiveUntil]");

                            t.HasCheckConstraint("CK_Referral_ParentCommission_Range", "[ParentCommission] IS NULL OR ([ParentCommission] >= 0 AND [ParentCommission] <= 100)");
                        });
                });

            modelBuilder.Entity("SFManagement.Models.Transactions.DigitalAssetTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("AssetAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("BalanceAs")
                        .HasColumnType("int");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("ConversionRate")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Rate")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<Guid>("ReceiverWalletIdentifierId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SenderWalletIdentifierId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Date")
                        .HasDatabaseName("IX_DigitalAssetTransaction_Date");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("IX_DigitalAssetTransaction_DeletedAt");

                    b.HasIndex("ReceiverWalletIdentifierId", "Date")
                        .HasDatabaseName("IX_DigitalAssetTransaction_Receiver_Date");

                    b.HasIndex("SenderWalletIdentifierId", "Date")
                        .HasDatabaseName("IX_DigitalAssetTransaction_Sender_Date");

                    b.ToTable("DigitalAssetTransactions", t =>
                        {
                            t.HasCheckConstraint("CK_DigitalAssetTransaction_AssetAmount_Positive", "[AssetAmount] > 0");

                            t.HasCheckConstraint("CK_DigitalAssetTransaction_Date_NotFuture", "[Date] <= GETDATE()");

                            t.HasCheckConstraint("CK_DigitalAssetTransaction_Different_Sender_Receiver", "[SenderWalletIdentifierId] <> [ReceiverWalletIdentifierId]");
                        });
                });

            modelBuilder.Entity("SFManagement.Models.Transactions.FiatAssetTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("AssetAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ReceiverWalletIdentifierId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SenderWalletIdentifierId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Date")
                        .HasDatabaseName("IX_FiatAssetTransaction_Date");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("IX_FiatAssetTransaction_DeletedAt");

                    b.HasIndex("ReceiverWalletIdentifierId", "Date")
                        .HasDatabaseName("IX_FiatAssetTransaction_Receiver_Date");

                    b.HasIndex("SenderWalletIdentifierId", "Date")
                        .HasDatabaseName("IX_FiatAssetTransaction_Sender_Date");

                    b.ToTable("FiatAssetTransactions", t =>
                        {
                            t.HasCheckConstraint("CK_FiatAssetTransaction_AssetAmount_Positive", "[AssetAmount] > 0");

                            t.HasCheckConstraint("CK_FiatAssetTransaction_Date_NotFuture", "[Date] <= GETDATE()");

                            t.HasCheckConstraint("CK_FiatAssetTransaction_Different_Sender_Receiver", "[SenderWalletIdentifierId] <> [ReceiverWalletIdentifierId]");
                        });
                });

            modelBuilder.Entity("SFManagement.Models.Transactions.ImportedTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("BaseAssetHolderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ExternalReferenceId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FileHash")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("FileMetadata")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("FileType")
                        .HasColumnType("int");

                    b.Property<Guid>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProcessingError")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("ReconciledAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ReconciledTransactionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("ReconciledTransactionType")
                        .HasColumnType("int");

                    b.Property<string>("ReconciliationNotes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BaseAssetHolderId")
                        .HasDatabaseName("IX_ImportedTransaction_BaseAssetHolderId");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("IX_ImportedTransaction_DeletedAt");

                    b.HasIndex("ExternalReferenceId")
                        .HasDatabaseName("IX_ImportedTransaction_ExternalReferenceId");

                    b.HasIndex("FileName")
                        .HasDatabaseName("IX_ImportedTransaction_FileName");

                    b.HasIndex("FileType")
                        .HasDatabaseName("IX_ImportedTransaction_FileType");

                    b.HasIndex("ReconciledTransactionId")
                        .HasDatabaseName("IX_ImportedTransaction_ReconciledTransactionId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_ImportedTransaction_Status");

                    b.HasIndex("Date", "Amount")
                        .HasDatabaseName("IX_ImportedTransaction_Date_Amount");

                    b.HasIndex("BaseAssetHolderId", "FileType", "Status")
                        .HasDatabaseName("IX_ImportedTransaction_BaseAssetHolder_FileType_Status");

                    b.ToTable("ImportedTransactions", t =>
                        {
                            t.HasCheckConstraint("CK_ImportedTransaction_Amount_Positive", "[Amount] >= 0");

                            t.HasCheckConstraint("CK_ImportedTransaction_Date_NotFuture", "[Date] <= GETDATE()");

                            t.HasCheckConstraint("CK_ImportedTransaction_FileSize_Positive", "[FileSizeBytes] IS NULL OR [FileSizeBytes] > 0");

                            t.HasCheckConstraint("CK_ImportedTransaction_ProcessedAt_Logic", "([Status] = 3 AND [ProcessedAt] IS NOT NULL) OR ([Status] <> 3 AND [ProcessedAt] IS NULL) OR [Status] = 3");

                            t.HasCheckConstraint("CK_ImportedTransaction_ReconciledAt_Logic", "([ReconciledTransactionId] IS NOT NULL AND [ReconciledAt] IS NOT NULL AND [ReconciledTransactionType] IS NOT NULL) OR ([ReconciledTransactionId] IS NULL AND [ReconciledAt] IS NULL AND [ReconciledTransactionType] IS NULL)");
                        });
                });

            modelBuilder.Entity("SFManagement.Models.Transactions.SettlementTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("AssetAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Rake")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("RakeBack")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RakeCommission")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ReceiverWalletIdentifierId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SenderWalletIdentifierId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Date")
                        .HasDatabaseName("IX_SettlementTransaction_Date");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("IX_SettlementTransaction_DeletedAt");

                    b.HasIndex("ReceiverWalletIdentifierId", "Date")
                        .HasDatabaseName("IX_SettlementTransaction_Receiver_Date");

                    b.HasIndex("SenderWalletIdentifierId", "Date")
                        .HasDatabaseName("IX_SettlementTransaction_Sender_Date");

                    b.ToTable("SettlementTransactions", t =>
                        {
                            t.HasCheckConstraint("CK_SettlementTransaction_AssetAmount_Positive", "[AssetAmount] > 0");

                            t.HasCheckConstraint("CK_SettlementTransaction_Date_NotFuture", "[Date] <= GETDATE()");

                            t.HasCheckConstraint("CK_SettlementTransaction_Different_Sender_Receiver", "[SenderWalletIdentifierId] <> [ReceiverWalletIdentifierId]");
                        });
                });

            modelBuilder.Entity("SFManagement.Models.AssetInfrastructure.AssetPool", b =>
                {
                    b.HasOne("SFManagement.Models.Entities.BaseAssetHolder", "BaseAssetHolder")
                        .WithMany("AssetPools")
                        .HasForeignKey("BaseAssetHolderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BaseAssetHolder");
                });

            modelBuilder.Entity("SFManagement.Models.AssetInfrastructure.WalletIdentifier", b =>
                {
                    b.HasOne("SFManagement.Models.AssetInfrastructure.AssetPool", "AssetPool")
                        .WithMany("WalletIdentifiers")
                        .HasForeignKey("AssetPoolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssetPool");
                });

            modelBuilder.Entity("SFManagement.Models.Entities.Bank", b =>
                {
                    b.HasOne("SFManagement.Models.Entities.BaseAssetHolder", "BaseAssetHolder")
                        .WithOne("Bank")
                        .HasForeignKey("SFManagement.Models.Entities.Bank", "BaseAssetHolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaseAssetHolder");
                });

            modelBuilder.Entity("SFManagement.Models.Entities.BaseAssetHolder", b =>
                {
                    b.HasOne("SFManagement.Models.Entities.BaseAssetHolder", "Referrer")
                        .WithMany()
                        .HasForeignKey("ReferrerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Referrer");
                });

            modelBuilder.Entity("SFManagement.Models.Entities.Client", b =>
                {
                    b.HasOne("SFManagement.Models.Entities.BaseAssetHolder", "BaseAssetHolder")
                        .WithOne("Client")
                        .HasForeignKey("SFManagement.Models.Entities.Client", "BaseAssetHolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaseAssetHolder");
                });

            modelBuilder.Entity("SFManagement.Models.Entities.Member", b =>
                {
                    b.HasOne("SFManagement.Models.Entities.BaseAssetHolder", "BaseAssetHolder")
                        .WithOne("Member")
                        .HasForeignKey("SFManagement.Models.Entities.Member", "BaseAssetHolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaseAssetHolder");
                });

            modelBuilder.Entity("SFManagement.Models.Entities.PokerManager", b =>
                {
                    b.HasOne("SFManagement.Models.Entities.BaseAssetHolder", "BaseAssetHolder")
                        .WithOne("PokerManager")
                        .HasForeignKey("SFManagement.Models.Entities.PokerManager", "BaseAssetHolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaseAssetHolder");
                });

            modelBuilder.Entity("SFManagement.Models.Support.Address", b =>
                {
                    b.HasOne("SFManagement.Models.Entities.BaseAssetHolder", null)
                        .WithMany("Addresses")
                        .HasForeignKey("BaseAssetHolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SFManagement.Models.Support.Category", b =>
                {
                    b.HasOne("SFManagement.Models.Support.Category", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("SFManagement.Models.Support.ContactPhone", b =>
                {
                    b.HasOne("SFManagement.Models.Entities.BaseAssetHolder", null)
                        .WithMany("ContactPhones")
                        .HasForeignKey("BaseAssetHolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SFManagement.Models.Support.InitialBalance", b =>
                {
                    b.HasOne("SFManagement.Models.Entities.BaseAssetHolder", "BaseAssetHolder")
                        .WithMany("InitialBalances")
                        .HasForeignKey("BaseAssetHolderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BaseAssetHolder");
                });

            modelBuilder.Entity("SFManagement.Models.Support.Referral", b =>
                {
                    b.HasOne("SFManagement.Models.Entities.BaseAssetHolder", "AssetHolder")
                        .WithMany("ReferralsMade")
                        .HasForeignKey("AssetHolderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SFManagement.Models.Entities.BaseAssetHolder", null)
                        .WithMany("ReferralsReceived")
                        .HasForeignKey("BaseAssetHolderId");

                    b.HasOne("SFManagement.Models.AssetInfrastructure.WalletIdentifier", "WalletIdentifier")
                        .WithMany("Referrals")
                        .HasForeignKey("WalletIdentifierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssetHolder");

                    b.Navigation("WalletIdentifier");
                });

            modelBuilder.Entity("SFManagement.Models.Transactions.DigitalAssetTransaction", b =>
                {
                    b.HasOne("SFManagement.Models.Support.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.HasOne("SFManagement.Models.AssetInfrastructure.WalletIdentifier", "ReceiverWalletIdentifier")
                        .WithMany()
                        .HasForeignKey("ReceiverWalletIdentifierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SFManagement.Models.AssetInfrastructure.WalletIdentifier", "SenderWalletIdentifier")
                        .WithMany()
                        .HasForeignKey("SenderWalletIdentifierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("ReceiverWalletIdentifier");

                    b.Navigation("SenderWalletIdentifier");
                });

            modelBuilder.Entity("SFManagement.Models.Transactions.FiatAssetTransaction", b =>
                {
                    b.HasOne("SFManagement.Models.Support.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.HasOne("SFManagement.Models.AssetInfrastructure.WalletIdentifier", "ReceiverWalletIdentifier")
                        .WithMany()
                        .HasForeignKey("ReceiverWalletIdentifierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SFManagement.Models.AssetInfrastructure.WalletIdentifier", "SenderWalletIdentifier")
                        .WithMany()
                        .HasForeignKey("SenderWalletIdentifierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("ReceiverWalletIdentifier");

                    b.Navigation("SenderWalletIdentifier");
                });

            modelBuilder.Entity("SFManagement.Models.Transactions.ImportedTransaction", b =>
                {
                    b.HasOne("SFManagement.Models.Entities.BaseAssetHolder", "BaseAssetHolder")
                        .WithMany("ImportedTransactions")
                        .HasForeignKey("BaseAssetHolderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BaseAssetHolder");
                });

            modelBuilder.Entity("SFManagement.Models.Transactions.SettlementTransaction", b =>
                {
                    b.HasOne("SFManagement.Models.Support.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.HasOne("SFManagement.Models.AssetInfrastructure.WalletIdentifier", "ReceiverWalletIdentifier")
                        .WithMany()
                        .HasForeignKey("ReceiverWalletIdentifierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SFManagement.Models.AssetInfrastructure.WalletIdentifier", "SenderWalletIdentifier")
                        .WithMany()
                        .HasForeignKey("SenderWalletIdentifierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("ReceiverWalletIdentifier");

                    b.Navigation("SenderWalletIdentifier");
                });

            modelBuilder.Entity("SFManagement.Models.AssetInfrastructure.AssetPool", b =>
                {
                    b.Navigation("WalletIdentifiers");
                });

            modelBuilder.Entity("SFManagement.Models.AssetInfrastructure.WalletIdentifier", b =>
                {
                    b.Navigation("Referrals");
                });

            modelBuilder.Entity("SFManagement.Models.Entities.BaseAssetHolder", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("AssetPools");

                    b.Navigation("Bank");

                    b.Navigation("Client");

                    b.Navigation("ContactPhones");

                    b.Navigation("ImportedTransactions");

                    b.Navigation("InitialBalances");

                    b.Navigation("Member");

                    b.Navigation("PokerManager");

                    b.Navigation("ReferralsMade");

                    b.Navigation("ReferralsReceived");
                });

            modelBuilder.Entity("SFManagement.Models.Support.Category", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
