name: Cleanup Artifacts

on:
  workflow_dispatch:

permissions:
  actions: write # Add explicit permissions to manage artifacts

jobs:
  delete-artifacts:
    runs-on: ubuntu-latest
    name: Delete Artifacts
    steps:
      - name: Delete all artifacts
        uses: geekyeggo/delete-artifact@v2
        with:
          failOnError: false
          name: .net-app
